config:
  framework: "hardhat" 
  framework_version: "^2.8.0" 

environment:
  PRIVATE_KEY: 000000000000000000000000000000000000000000000000000000000000dead # Fake private key to make the build pass

tasks:
  install-dependencies:
    - npm install --legacy-peer-deps

